added description and state prop
a-ui/core_components_react pull request #6
Opened 2023-08-23 14:57 UTC by AlecVanSteenbrugge

Autocomplete can pass the description and state prop so users will be notified when they have a faulty result in there TextField.

2023-08-24 07:03 UTC, TriangleJuice requested changes
Thanks for your pull request and helping us creating the most solid design system for the city of Antwerp! I've suggested a few changes, related to linting rules.

Could you please also do the following things:

- Add the new feature to the documentation (in Autocomplete.stories.jsx)
- Add a CHANGELOG entry (under "Unreleased")

2023-08-24 07:03 UTC, TriangleJuice commented on packages/antwerp-ui/react-components/src/lib/molecules/autocomplete/Autocomplete.types.ts
> +  state?:'error'|'success'
```suggestion
  description?: string;
  state?: 'error' | 'success'
```

2023-08-24 09:19 UTC, TriangleJuice approved these changes

2023-08-24 09:29 UTC, NicolasYapla commented
@AlecVanSteenbrugge Can you update this in the documentation of Autocomplete as well? It's in the Autocomplete.stories.jsx file.

2023-08-24 11:33 UTC, TriangleJuice requested changes
Er zijn nog git merge issues

2023-08-24 12:09 UTC, AlecVanSteenbrugge commented
> Er zijn nog git merge issues

i've corrected this in 37ceff9, my appologies but now there shoudn't be any merge issues.

2023-08-24 12:21 UTC, TriangleJuice approved these changes

2023-08-24 12:22 UTC, TriangleJuice commented
> > Er zijn nog git merge issues
> 
> i've corrected this in [37ceff9](https://github.com/a-ui/core_components_react/commit/37ceff9f8c1f4b2ea6b431329ffb54536534f2a8), my appologies but now there shoudn't be any merge issues.

No apologies needed! Thank you for fixing it.
@NicolasYapla Ok for you now?

2023-08-25 09:43 UTC, NicolasYapla commented
Looks good, I merge it. Will be published in next version.

2023-08-25 09:43 UTC, merged