allow autoComplete prop on TextField component
a-ui/core_components_react pull request #7
Opened 2023-09-29 16:26 UTC by wouterlanduydt

Allows to pass autoComplete prop to TextField component and disables it on the Autocomplete component since otherwise the user can be faced with the default browser autoComplete (see screenshot).

Also makes sure that using arrows to select listitems in the Flyout doesn't affect the cursor position in the TextField.

<img width="690" alt="Screenshot 2023-09-28 at 14 17 29" src="https://github.com/a-ui/core_components_react/assets/23736231/b9f05c4d-1061-4f0b-a0eb-e294c912bf19">

2023-09-30 09:21 UTC, TriangleJuice requested changes
Thanks for the "arrow fix"!

The autocomplete "fix" however is something we omitted on purpose. Browser support is to say the least wonky: https://caniuse.com/input-autocomplete-onoff

2023-10-02 07:13 UTC, wouterlanduydt commented
Thanks for the quick response @TriangleJuice .

Hmm I understand autocomplete browser support is a bit sketchy, but shouldn't the browser autocomplete be disabled in a way when we're building a custom Autocomplete component?

Imo the fix I proposed for this component outweighs the issues that might be introduced by wonky browser support.

2023-10-02 07:56 UTC, NicolasYapla approved these changes

2023-10-02 10:40 UTC, TriangleJuice approved these changes

2023-10-05 14:21 UTC, merged

2023-10-05 14:22 UTC, NicolasYapla commented
Merged it, will be released pretty soon in next version 7.1.0